import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "YouTube Guesser - DEV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className="bg-gray-100 min-h-screen">{children}</body>
    </html>
  );
}
